# 配置连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minreview
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liu6713122616.
  # 处理网络请求大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  main:
    allow-circular-references: true

# 服务端口
server:
  port: 8080

# 配置mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# 配置日志级别
logging:
  org.springframework.jdbc.support.JdbcTransactionManager: debug

min:
  review:
    secretKey: pengzhiliu
    ttlTime: 86400000





