# 配置连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minreview
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liu6713122616.
  # 处理网络请求大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  main:
    allow-circular-references: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 2
      password: 123456

# 服务端口
server:
  port: 8080

# 配置mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# 配置日志级别
logging:
  level:
    dev.langchain4j: debug
    org.springframework.jdbc.support.JdbcTransactionManager: debug

min:
  review:
    secretKey: pengzhiliu
    ttlTime: 86400000
#    ttlTime: 10000

    aliyunoss:
      bucket-name: liu-sunset-sky-take-out
      endpoint: https://oss-cn-beijing.aliyuncs.com
      region: cn-beijing

langchain4j:
  open-ai:
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: deepseek-v3
      api-key: ${API-KEY}
      log-requests: true
      log-responses: true

